repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
