name: Docker Image CI

on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t qinbatista/download .

      - uses: docker/login-action@v2
      - name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
      - name: Build and push
        with:
          push: true
          tags: user/app:latest
