name: Docker Image CI

on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ubuntu
    steps:
      - name: Build and Push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: qinbatista/download
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
